[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_GEMINI_API_KEY"
  SECRETS_SCAN_ENABLED = "false"
